### ISSUE TITLE
Problem with gasDetails

### ISSUE THREAD

**Issue by SakovichVl** [etherspot/etherspot-prime-sdk#25]
On the local version of my application, the operations are sending maxFeePerGas: 0x01. On the hosted version the gas cost is already with an adequate value.
I decided to specify explicit constant values for the gas cost. It turned out that you can't specify them, because your code overwrites my passed values first by 1 and then by the values from the bundler if they exist

```
async estimate(gasDetails?: TransactionGasInfoForUserOp) {
    if (this.userOpsBatch.to.length < 1) {
      throw new Error("cannot sign empty transaction batch");
    }

    const tx: TransactionDetailsForUserOp = {
      target: this.userOpsBatch.to,
      values: this.userOpsBatch.value,
      data: this.userOpsBatch.data,
      ...gasDetails,
    }

    let partialtx = await this.etherspotWallet.createUnsignedUserOp({
      ...tx,
      maxFeePerGas: 1,
      maxPriorityFeePerGas: 1,
    });
    
    
```
This is where you overwrite the value of the custom gasDetails
What you probably wanted to do?
   let partialtx = await this.etherspotWallet.createUnsignedUserOp({
         maxFeePerGas: 1,
         maxPriorityFeePerGas: 1,
         ...tx,
    });
    Next is the code that completely conflicts with the custom value of gas in transactions
```
    const bundlerGasEstimate = await this.bundler.getVerificationGasInfo(partialtx);

    // if estimation has gas prices use them, otherwise fetch them in a separate call
    if (bundlerGasEstimate.maxFeePerGas && bundlerGasEstimate.maxPriorityFeePerGas) {
      partialtx.maxFeePerGas = bundlerGasEstimate.maxFeePerGas;
      partialtx.maxPriorityFeePerGas = bundlerGasEstimate.maxPriorityFeePerGas;
    } else {
      const gas = await this.getGasFee();
      partialtx.maxFeePerGas = gas.maxFeePerGas;
      partialtx.maxPriorityFeePerGas = gas.maxPriorityFeePerGas;
    }

    if (bundlerGasEstimate.preVerificationGas) {
      partialtx.preVerificationGas = BigNumber.from(bundlerGasEstimate.preVerificationGas);
      partialtx.verificationGasLimit = BigNumber.from(bundlerGasEstimate.verificationGasLimit ?? bundlerGasEstimate.verificationGas);
      partialtx.callGasLimit = BigNumber.from(bundlerGasEstimate.callGasLimit);
    }

    return partialtx;

  }
```

In view of the whole situation, I am worried about two questions
1. what does the value of bundlerGasEstimate depend on?
2. Is not being able to install custom gas a bug?

**Comment by SakovichVl** [comment]
@vignesha22 Is there any news?

**Comment by vignesha22** [comment]
yes we are looking into it and the PR will be generated in a weeks time as we are planning to make a release next week.

**Comment by SakovichVl** [comment]
tnx a lot for answer

**Comment by arddluma** [comment]
hey @SakovichVl ,
Thanks again for reporting this issue.
Could you please check version 1.26.6, hopefully this should fix it

**Comment by SakovichVl** [comment]
@arddluma Can we discuss version in discord?

**Comment by arddluma** [comment]
As confirmed in discord. everything working as expected. closing this ticket. Thanks again @SakovichVl
