### ISSUE TITLE
getAccountBalances throwing error

### ISSUE THREAD

**Issue by shazzar-ox** [etherspot/etherspot-prime-sdk#41]
Hi,

i have been  trying to get all account balances and it keeps throwing me an error 

error: failed to execute "open" on xmlhttprequest : invalid URL.

i use node v.20 and next 13.5.4..

how do i fix this?

**Comment by kaushalrajbacancy** [comment]
@shazzar-ox  Can you please specify the **chainId** which you are using to initialize the **primeSDK**?

**Comment by shazzar-ox** [comment]
Sepolia: 11155111

**Comment by kaushalrajbacancy** [comment]
@shazzar-ox  Can you please try some other chains? Like, **goerli: 5, mumbai: 80001**.

**Comment by shazzar-ox** [comment]
I’m getting invalid project key. Do you mind letting me know what the project key is meant to be.

**Comment by kaushalrajbacancy** [comment]
> I’m getting invalid project key. Do you mind letting me know what the project key is meant to be.

- A project key serves as a secure code that functions to identify and authenticate either an application or user when accessing data wrapper endpoints.

You require a valid project key to access the data wrapper endpoints.

**Comment by shazzar-ox** [comment]
How do I get it please. Or where do I get one

**Comment by arddluma** [comment]
> How do I get it please. Or where do I get one

hey,
Please create a ticket in our Discord https://discord.etherspot.io

**Comment by shazzar-ox** [comment]
Gotten. Thank you
