### ISSUE TITLE
Unsupported network error when initializing custom chain in Prime SDK [BUG] 

### ISSUE THREAD

**Issue by 0xAnto** [etherspot/etherspot-prime-sdk#73]
### Describe the bug

I am encountering an "Unsupported network" error when attempting to initialize a custom chain using the Prime SDK. This issue seems to occur during the initialization process with the provided configuration.

### Expected behavior

I expected the Prime SDK to successfully initialize the custom chain with the provided parameters, connecting to the specified network without encountering an "Unsupported network" error.

### Steps to reproduce

1. Initialize the Prime SDK with the following configuration:
```const primeSdk = new PrimeSdk(
   { privateKey: process.env.WALLET_PRIVATE_KEY },
   {
      chainId: 49088,
      projectKey: 'public-prime-testnet-key',
      entryPointAddress: '0x793949275B35D3E394f5C218DC88ae6C7D04a252',
      bundlerRpcUrl: 'https://bifrost-testnet-bundler.kanalabs.io/',
      factoryWallet: Factory.ETHERSPOT,
      walletFactoryAddress: '0x91037ED7B25d72F61B80D4376C0E66680997Ce5E',
   },
);
```

2. Observe the "Unsupported network" error during initialization.

### code
![image](https://github.com/etherspot/etherspot-prime-sdk/assets/72078695/41be0144-4092-48bb-aaaa-99490b82510a)

### error
![image](https://github.com/etherspot/etherspot-prime-sdk/assets/72078695/576714b7-908d-4492-affb-ca13d3014e80)

### Operating system

Windows

### Prime SDK version or commit hash

v1.3.12

**Comment by ch4r10t33r** [comment]
Thanks for reporting @0xAnto . We should have a fix ready for this shortly.
