### ISSUE TITLE
[BUG] how to reuse later in the code the same instance of an new PrimeSdk()  ?

### ISSUE THREAD

**Issue by francelwebdev** [etherspot/etherspot-prime-sdk#78]
### Describe the bug

how to reuse later in the code the same instance of an new PrimeSdk()  ?

### Expected behavior

reuse the same instance of new PrimeSdk()  ?

### Operating system

Linux

### Prime SDK version or commit hash

latest

**Comment by ch4r10t33r** [comment]
Thanks for reporting the issue @francelwebdev . Please can you elaborate this more? What exactly is the issue you are facing? Is there a code snippet that demonstrate the issue?
