### ISSUE TITLE
[BUG] this library work in server side nodejs api

### ISSUE THREAD

**Issue by francelwebdev** [etherspot/etherspot-prime-sdk#79]
### Describe the bug

I'm getting this error on : await primeSdk.estimate()

checking nonce...
2 | Object.defineProperty(exports, "__esModule", { value: true });
3 | exports.ErrorHandler = void 0;
4 | const constants_1 = require("./constants");
5 | class ErrorHandler extends Error {
6 |     constructor(error, code) {
7 |         super(error);
            ^
error: AA21 didn't pay prefund
 code: "-32500"

      at new ErrorHandler (/home/francel/Bureau/etherspot_prime_test/node_modules/@etherspot/prime-sdk/dist/sdk/errorHandler/errorHandler.service.js:7:8)
      at /home/francel/Bureau/etherspot_prime_test/node_modules/@etherspot/prime-sdk/dist/sdk/base/HttpRpcClient.js:41:22
      at processTicksAndRejections (:61:76)

### Expected behavior

Work well inserver side nodejs

### Operating system

Linux

### Prime SDK version or commit hash

latest

**Comment by ch4r10t33r** [comment]
> I'm getting this error on : await primeSdk.estimate()
> 
> checking nonce... 2 | Object.defineProperty(exports, "__esModule", { value: true }); 3 | exports.ErrorHandler = void 0; 4 | const constants_1 = require("./constants"); 5 | class ErrorHandler extends Error { 6 | constructor(error, code) { 7 | super(error); ^ error: AA21 didn't pay prefund code: "-32500"

This is a valid error which means the wallet you are using doesn't have enough balance to pay for the gas. I suggest you look at examples provided in `https://github.com/etherspot/etherspot-prime-sdk/examples` and work from there.

**Comment by ch4r10t33r** [comment]
Please refer to `https://etherspot.fyi/contracts/error-codes` that lists all the common error codes.
