### ISSUE TITLE
Invalid Wallet Provider [BUG] 

### ISSUE THREAD

**Issue by Linux-Server** [etherspot/etherspot-prime-sdk#86]
<img width="1440" alt="Screenshot 2023-12-07 at 2 30 50 PM" src="https://github.com/etherspot/etherspot-prime-sdk/assets/67502584/29ff0dbb-3817-4008-bd24-ec329f452992">
### Describe the bug

Invalid wallet provider
    at new PrimeSdk 

### Expected behavior

Im trying to inistantiate the prive sdk with "npm run 01-get-address"
`
import { PrimeSdk } from '../src';
import * as dotenv from 'dotenv';

dotenv.config();

async function main() {
  // initializating sdk...
  const primeSdk = new PrimeSdk({ privateKey: process.env.WALLET_PRIVATE_KEY }, { chainId: Number(process.env.CHAIN_ID), projectKey: 'public-prime-testnet-key' })

  // get EtherspotWallet address...
  const address: string = await primeSdk.getCounterFactualAddress();
  console.log('\x1b[33m%s\x1b[0m', `EtherspotWallet address: ${address}`);
}

main()
  .catch(console.error)
  .finally(() => process.exit());

`

### Operating system

macOS

### Prime SDK version or commit hash

1.3.13

**Comment by arddluma** [comment]
> <img alt="Screenshot 2023-12-07 at 2 30 50 PM" width="1440" src="https://private-user-images.githubusercontent.com/67502584/288698811-29ff0dbb-3817-4008-bd24-ec329f452992.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NDE4NjcsIm5iZiI6MTcwMTk0MTU2NywicGF0aCI6Ii82NzUwMjU4NC8yODg2OTg4MTEtMjlmZjBkYmItMzgxNy00MDA4LWJkMjQtZWMzMjlmNDUyOTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDA5MzI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNmMzMTc5Y2UwMWYyODdhOWFkZGU3ZWIwMjY4ZmEyMWVkMmQ2YzI1NWZlNTUxZTY2NTUzNGYxMjI0ZjJjN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vqZwhl84qpJcj1TceKV9hCf64imz_Wxftvipyy-rreA"> ### Describe the bug
> Invalid wallet provider at new PrimeSdk
> 
> ### Expected behavior
> Im trying to inistantiate the prive sdk with "npm run 01-get-address" ` import { PrimeSdk } from '../src'; import * as dotenv from 'dotenv';
> 
> dotenv.config();
> 
> async function main() { // initializating sdk... const primeSdk = new PrimeSdk({ privateKey: process.env.WALLET_PRIVATE_KEY }, { chainId: Number(process.env.CHAIN_ID), projectKey: 'public-prime-testnet-key' })
> 
> // get EtherspotWallet address... const address: string = await primeSdk.getCounterFactualAddress(); console.log('\x1b[33m%s\x1b[0m', `EtherspotWallet address: ${address}`); }
> 
> main() .catch(console.error) .finally(() => process.exit());
> 
> `
> 
> ### Steps to reproduce
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Operating system
> macOS
> 
> ### Prime SDK version or commit hash
> 1.3.13

hello there,
thanks for creating issue on GitHub.
Have you set WALLET_PRIVATE_KEY in .env and CHAIN_ID ? Keep in mind priv key should start with 0x...

**Comment by Linux-Server** [comment]
> > <img alt="Screenshot 2023-12-07 at 2 30 50 PM" width="1440" src="https://private-user-images.githubusercontent.com/67502584/288698811-29ff0dbb-3817-4008-bd24-ec329f452992.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NDE4NjcsIm5iZiI6MTcwMTk0MTU2NywicGF0aCI6Ii82NzUwMjU4NC8yODg2OTg4MTEtMjlmZjBkYmItMzgxNy00MDA4LWJkMjQtZWMzMjlmNDUyOTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDA5MzI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNmMzMTc5Y2UwMWYyODdhOWFkZGU3ZWIwMjY4ZmEyMWVkMmQ2YzI1NWZlNTUxZTY2NTUzNGYxMjI0ZjJjN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vqZwhl84qpJcj1TceKV9hCf64imz_Wxftvipyy-rreA"> ### Describe the bug
> > Invalid wallet provider at new PrimeSdk
> > ### Expected behavior
> > Im trying to inistantiate the prive sdk with "npm run 01-get-address" ` import { PrimeSdk } from '../src'; import * as dotenv from 'dotenv';
> > dotenv.config();
> > async function main() { // initializating sdk... const primeSdk = new PrimeSdk({ privateKey: process.env.WALLET_PRIVATE_KEY }, { chainId: Number(process.env.CHAIN_ID), projectKey: 'public-prime-testnet-key' })
> > // get EtherspotWallet address... const address: string = await primeSdk.getCounterFactualAddress(); console.log('\x1b[33m%s\x1b[0m', `EtherspotWallet address: ${address}`); }
> > main() .catch(console.error) .finally(() => process.exit());
> > `
> > ### Steps to reproduce
> > _No response_
> > ### Additional context
> > _No response_
> > ### Operating system
> > macOS
> > ### Prime SDK version or commit hash
> > 1.3.13
> 
> hello there, thanks for creating issue on GitHub. Have you set WALLET_PRIVATE_KEY in .env and CHAIN_ID ? Keep in mind priv key should start with 0x...

It's working now, but it should mentioned in that prime sdk docs..

**Comment by arddluma** [comment]
> > > <img alt="Screenshot 2023-12-07 at 2 30 50 PM" width="1440" src="https://private-user-images.githubusercontent.com/67502584/288698811-29ff0dbb-3817-4008-bd24-ec329f452992.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NDE4NjcsIm5iZiI6MTcwMTk0MTU2NywicGF0aCI6Ii82NzUwMjU4NC8yODg2OTg4MTEtMjlmZjBkYmItMzgxNy00MDA4LWJkMjQtZWMzMjlmNDUyOTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDA5MzI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNmMzMTc5Y2UwMWYyODdhOWFkZGU3ZWIwMjY4ZmEyMWVkMmQ2YzI1NWZlNTUxZTY2NTUzNGYxMjI0ZjJjN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vqZwhl84qpJcj1TceKV9hCf64imz_Wxftvipyy-rreA"> ### Describe the bug
> > > Invalid wallet provider at new PrimeSdk
> > > ### Expected behavior
> > > Im trying to inistantiate the prive sdk with "npm run 01-get-address" `import { PrimeSdk } from '../src'; import * as dotenv from 'dotenv'; dotenv.config(); async function main() { // initializating sdk... const primeSdk = new PrimeSdk({ privateKey: process.env.WALLET_PRIVATE_KEY }, { chainId: Number(process.env.CHAIN_ID), projectKey: 'public-prime-testnet-key' }) // get EtherspotWallet address... const address: string = await primeSdk.getCounterFactualAddress(); console.log('\x1b[33m%s\x1b[0m',`EtherspotWallet address: ${address}`); } main() .catch(console.error) .finally(() => process.exit()); `
> > > ### Steps to reproduce
> > > _No response_
> > > ### Additional context
> > > _No response_
> > > ### Operating system
> > > macOS
> > > ### Prime SDK version or commit hash
> > > 1.3.13
> > 
> > 
> > hello there, thanks for creating issue on GitHub. Have you set WALLET_PRIVATE_KEY in .env and CHAIN_ID ? Keep in mind priv key should start with 0x...
> 
> It's working now, but it should mentioned in that prime sdk docs..

good point! we gonna improve the docs. thank you!
